/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type FaqItem = {
  _type: "faqItem"
  question?: string
  answer?: string
}

export type ArticleSection = {
  _type: "articleSection"
  heading?: string
  paragraphs?: Array<string>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  publishedOn?: string
  readTime?: string
  intro?: string
  sections?: Array<
    {
      _key: string
    } & ArticleSection
  >
  faqs?: Array<
    {
      _key: string
    } & FaqItem
  >
  featured?: boolean
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | FaqItem
  | ArticleSection
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../lib/sanity/queries.ts
// Variable: BLOG_COUNT_QUERY
// Query: count(*[_type == "post" && defined(slug.current)])
export type BLOG_COUNT_QUERY_RESULT = number

// Source: ../lib/sanity/queries.ts
// Variable: BLOG_FEATURED_QUERY
// Query: *[_type == "post" && defined(slug.current) && featured == true]  | order(publishedOn desc) [0...3] {      _id,  title,  "slug": slug.current,    coverImage {    alt,    hotspot,    crop,    asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height }      }    }  }  }
export type BLOG_FEATURED_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  coverImage: {
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number | null
          height: number | null
        } | null
      } | null
    } | null
  } | null
}>

// Source: ../lib/sanity/queries.ts
// Variable: BLOG_LATEST_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(publishedOn desc) [0...3] {      _id,  title,  "slug": slug.current,    coverImage {    alt,    hotspot,    crop,    asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height }      }    }  }  }
export type BLOG_LATEST_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  coverImage: {
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number | null
          height: number | null
        } | null
      } | null
    } | null
  } | null
}>

// Source: ../lib/sanity/queries.ts
// Variable: BLOG_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{    "slug": slug.current  }
export type BLOG_SLUGS_QUERY_RESULT = Array<{
  slug: string | null
}>

// Source: ../lib/sanity/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    readTime,    publishedOn,    intro,    featured,      coverImage {    alt,    hotspot,    crop,    asset->{      _id,      url,      metadata {        lqip,        dimensions { width, height }      }    }  },    sections[]{      _key,      heading,      paragraphs    },    faqs[]{      _key,      question,      answer    }  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: string | null
  readTime: string | null
  publishedOn: string | null
  intro: string | null
  featured: boolean | null
  coverImage: {
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number | null
          height: number | null
        } | null
      } | null
    } | null
  } | null
  sections: Array<{
    _key: string
    heading: string | null
    paragraphs: Array<string> | null
  }> | null
  faqs: Array<{
    _key: string
    question: string | null
    answer: string | null
  }> | null
} | null

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  count(*[_type == "post" && defined(slug.current)])\n': BLOG_COUNT_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current) && featured == true]\n  | order(publishedOn desc) [0...3] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  \n  coverImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height }\n      }\n    }\n  }\n\n\n  }\n': BLOG_FEATURED_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(publishedOn desc) [0...3] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  \n  coverImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height }\n      }\n    }\n  }\n\n\n  }\n': BLOG_LATEST_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': BLOG_SLUGS_QUERY_RESULT
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    readTime,\n    publishedOn,\n    intro,\n    featured,\n    \n  coverImage {\n    alt,\n    hotspot,\n    crop,\n    asset->{\n      _id,\n      url,\n      metadata {\n        lqip,\n        dimensions { width, height }\n      }\n    }\n  }\n,\n    sections[]{\n      _key,\n      heading,\n      paragraphs\n    },\n    faqs[]{\n      _key,\n      question,\n      answer\n    }\n  }\n': BLOG_POST_QUERY_RESULT
  }
}
